from typing import Protocol, AsyncIterator, Any

class ModelProvider(Protocol):
    async def load(self) -> None: ...
    async def unload(self) -> None: ...
    async def generate(self, prompt: str, **kwargs: Any) -> str: ...
    async def stream(self, prompt: str, **kwargs: Any) -> AsyncIterator[str]: ...
    async def health(self) -> bool: ...
    def metadata(self) -> dict: ...
